# -*- coding: utf-8 -*-
"""
Created on Tue May  9 12:24:56 2023

@author: mokuneva
"""

def unicode_correct_welt(text):
    
    """This function corrects the unicode errors present in the database."""
    
    # Correct the unicode errors.
    correct_unicode_dic = {
        "{sbquo}": "'",
        "Ha{ring}kan": "Håkan",
        "A{ring}sa": "Åsa",
        "Stra{ring}berg": "Stråberg",
        "Jan-A{ring}ke": "Jan-Åke",
        "Ha{ring}kann": "Håkan",
        "u{cech}": "ǔ",
        "a{cech}": "ǎ",
        "s{cech}": "š",
        "o{cech}": "ŏ",
        "c{ogon}": "ç",
        "{circ}": "",
        'f��r': 'für',
        'k��nnen': 'können',
        'j��hrlich': 'jährlich',
        'Gro��britannien': 'Großbritannien',
        '��ber': 'über',
        'Ma��nahme': 'Maßnahme',
        '��hnlichen': 'ähnlichen',
        'f��hren': 'führen',
        'Roh��lpreis': 'Rohölpreis',
        'ans��ssig': 'ansässig',
        'franz��sischen': 'französischen',
        'Qualit��t': 'Qualität',
        'S��dwesten': 'Südwesten',
        'Ums��tze': 'Umsätze',
        'f��rdernd': 'fördernd',
        'M��nchner': 'Münchner',
        'Kreditausf��lle': 'Kreditausfälle',
        'Ver��ffentlichung': 'Veröffentlichung',
        'gr��ßte': 'größte',
        'Ausl��ser': 'Auslöser',
        'Generalsekret��r': 'Generalsekretär',
        'Poppenb��ttel': 'Poppenbüttel',
        'gl��hen': 'glühen',
        'gro��en': 'großen',
        'abh��ngig': 'abhängig',
        'Marktverh��ltnisse': 'Marktverhältnisse',
        'Wirtschaftsverb��nde': 'Wirtschaftsverbände',
        'Unverst��ndnis': 'Unverständnis',
        'einf��hrte': 'einführte',
        'vern��nftig': 'vernünftig',
        'w��re': 'wäre',
        'bef��rchteten': 'befürchteten',
        'B��rse': 'Börse',
        'd��rfte': 'dürfte',
        'f��hlt': 'fühlt',
        'emp��rt': 'empört',
        'Dr��gerwerk': 'Drägerwerk',
        'Rentenm��rkte': 'Rentenmärkte',
        'Kapitalm��rkte': 'Kapitalmärkte',
        'Marktf��hrer': 'Marktführer',
        'fr��h': 'früh',
        'europ��ischen': 'europäischen',
        'Fr��hjahr': 'Frühjahr',
        'sch��nsten': 'schönsten',
        '��bermitteln': 'übermitteln',
        'Landesb��rgschaft': 'Landesbürgschaft',
        'verst��rkt': 'verstärkt',
        'Gesch��ft': 'Geschäft',
        'Sü��ware': 'Süßware',
        'gro��e': 'große',
        '��berprüft': 'überprüft',
        'S��ulen': 'Säulen',
        'h��rt': 'hört',
        'W��hrung': 'Währung',
        'k��nnten': 'könnten',
        'Pilgerst��tten': 'Pilgerstätten',
        'f��llig': 'fällig',
        'Hauptgesch��ftsführer': 'Hauptgeschäftsführer',
        'Eigent��mer': 'Eigentümer',
        'zur��ck': 'zurück',
        'ungew��hnliche': 'ungewöhnliche',
        'L��er': 'Läer',
        'f��nf': 'fünf',
        'Rechtsanw��lte': 'Rechtsanwälte',
        'B��rger': 'Bürger',
        'Selbstst��ndigkeit': 'Selbstständigkeit',
        'Gesch��ftsjahr': 'Geschäftsjahr',
        'Großhandelsm��rkten': 'Großhandelsmärkten',
        'Dar��ber': 'Darüber',
        'Preisr��ckgangs': 'Preisrückgangs',
        '��l': 'Öl',
        'F��hrungspositionen': 'Führungspositionen',
        'unabh��ngigen': 'unabhängigen',
        'fr��heren': 'früheren',
        'Besch��ftigte': 'Beschäftigte',
        'k��nnte': 'könnte',
        'F��lle': 'Fälle',
        'sozialvertr��glich': 'sozialverträglich',
        'hei��t': 'heißt',
        'j��ngsten': 'jüngsten',
        'Hochgeschwindigkeitsz��ge': 'Hochgeschwindigkeitszüge',
        'abschw��cht': 'abschwächt',
        'geh��ren': 'gehören',
        'Übersch��sse': 'Überschüsse',
        '��bertragung': 'Übertragung',
        'Niederl��nder': 'Niederländer',
        'f��rchten': 'fürchten',
        '��rtlichen': 'örtlichen',
        'k��men': 'kämen',
        'Telefongespr��che': 'Telefongespräche',
        'm��ssen': 'müssen',
        'Produktivit��t': 'Produktivität',
        'zus��tzlicher': 'zusätzlicher',
        'gegenw��rtig': 'gegenwärtig',
        'europ��ische': 'europäische',
        'K��chenausstatters': 'Küchenausstatters',
        'L��ndern': 'Ländern',
        'St��dte': 'Städte',
        '��berschuss': 'Überschuss',
        '��bergangs': 'Übergangs',
        'Gr��nder': 'Gründer',
        'H��ndler': 'Händler',
        'h��tte': 'hätte',
        '��ffentlichkeit': 'Öffentlichkeit',
        'Hauptgeschäftsf��hrer': 'Hauptgeschäftsführer',
        'r��ckten': 'rückten',
        'fr��herer': 'früherer',
        'Gro��raumflugzeugen': 'Großraumflugzeugen',
        'h��her': 'höher',
        'H��he': 'Höhe',
        'grö��ten': 'größten',
        'f��nde': 'fände',
        'abschw��chen': 'abschwächen'}
    
    for mistake, correction in correct_unicode_dic.items():
        text = text.replace(mistake, correction)                  
    
    return(text)